"use client";

import Navbar from "@/components/Navbar";
import Link from "next/link";

export default function ExecutiveDashboardPage() {
  return (
    <>
      <Navbar />

      <main className="min-h-screen bg-black px-6 py-32 text-white">

        <div className="mx-auto max-w-7xl">

          <div className="text-center">

            <p className="text-sm uppercase tracking-[0.4em] text-cyan-400">
              EXECUTIVE DASHBOARD
            </p>

            <h1 className="mt-6 text-5xl font-bold md:text-7xl">
              Business Command Center
            </h1>

            <p className="mx-auto mt-8 max-w-3xl text-lg text-gray-400">
              Unified visibility into revenue, leads, customer support,
              business intelligence, and AI operations.
            </p>

          </div>

          <div className="mt-20 grid gap-6 md:grid-cols-2 xl:grid-cols-4">

            {[
              ["₹24.8L", "Revenue"],
              ["52", "Qualified Leads"],
              ["42", "Support Tickets"],
              ["1,284", "Active Customers"],
            ].map(([value, label]) => (

              <div
                key={label}
                className="rounded-[2rem] border border-white/10 bg-white/[0.03] p-8"
              >
                <h2 className="text-5xl font-bold text-blue-400">
                  {value}
                </h2>

                <p className="mt-4 text-gray-400">
                  {label}
                </p>

              </div>

            ))}

          </div>

          <div className="mt-16 grid gap-8 lg:grid-cols-2">

            <div className="rounded-[2rem] border border-white/10 bg-white/[0.03] p-8">

              <h2 className="mb-8 text-3xl font-semibold">
                Agent Summary
              </h2>

              <div className="space-y-5">

                <div>Athena — Reporting & Analytics</div>
                <div>Orion — Sales Intelligence</div>
                <div>Nova — Customer Support</div>
                <div>Sentinel — Lead Qualification</div>

              </div>

            </div>

            <div className="rounded-[2rem] border border-white/10 bg-white/[0.03] p-8">

              <h2 className="mb-8 text-3xl font-semibold">
                Activity Feed
              </h2>

              <div className="space-y-5">

                <div>Lead qualified by Sentinel</div>
                <div>Proposal generated by Orion</div>
                <div>Support issue resolved by Nova</div>
                <div>Market report generated by Athena</div>

              </div>

            </div>

          </div>

          <div className="mt-16 flex flex-wrap justify-center gap-4">

  <Link
    href="/command-center"
    className="rounded-full bg-blue-600 px-8 py-4 font-medium"
  >
    Command Center
  </Link>

  <Link
    href="/ai-agents"
    className="rounded-full border border-white/10 px-8 py-4"
  >
    AI Agents
  </Link>

  <Link
    href="/lead-agent"
    className="rounded-full border border-white/10 px-8 py-4"
  >
    Lead Agent
  </Link>

  <Link
    href="/sales-agent"
    className="rounded-full border border-white/10 px-8 py-4"
  >
    Sales Agent
  </Link>

</div>
          <div className="mt-16 rounded-[2rem] border border-white/10 bg-white/[0.03] p-8">

  <h2 className="mb-8 text-3xl font-semibold">
    Agent Performance
  </h2>

  <div className="space-y-8">

    {[
      ["Athena", "99.2"],
      ["Orion", "98.0"],
      ["Nova", "96.1"],
      ["Sentinel", "92.4"],
    ].map(([agent, value]) => (

      <div key={agent}>

        <div className="mb-2 flex justify-between">
          <span>{agent}</span>
          <span className="text-cyan-400">{value}%</span>
        </div>

        <div className="h-3 rounded-full bg-white/10">
          <div
            className="h-3 rounded-full bg-blue-500"
            style={{
              width: `${value}%`,
            }}
          />
        </div>

      </div>

    ))}

  </div>

</div>
<div className="mt-16 rounded-[2rem] border border-white/10 bg-white/[0.03] p-8">

  <h2 className="mb-8 text-3xl font-semibold">
    Sales Pipeline
  </h2>

  <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">

    {[
      ["Discovery Calls", "₹4.2L"],
      ["Qualified Leads", "₹9.8L"],
      ["Proposal Stage", "₹14.4L"],
      ["Negotiation", "₹21.2L"],
    ].map(([stage, value]) => (

      <div
        key={stage}
        className="rounded-2xl border border-white/10 p-6"
      >

        <p className="text-gray-400">
          {stage}
        </p>

        <h3 className="mt-3 text-3xl font-bold text-green-400">
          {value}
        </h3>

      </div>

    ))}

  </div>

</div>
<div className="mt-16 rounded-[2rem] border border-blue-500/20 bg-blue-500/[0.05] p-8">

  <p className="mb-4 text-sm uppercase tracking-[0.3em] text-cyan-400">
    EXECUTIVE SUMMARY
  </p>

  <div className="space-y-4 text-lg text-gray-300">

    <p>
      • Revenue increased 18% compared to last month
    </p>

    <p>
      • Lead qualification efficiency improved by 12%
    </p>

    <p>
      • Customer support resolution rate reached 96%
    </p>

    <p>
      • AI automation saved an estimated 220 hours
    </p>

  </div>

</div>

        </div>

      </main>
    </>
  );
}